# Generated by Django 3.2.12 on 2025-01-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
