# Generated by Django 3.2.12 on 2025-02-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USers', '0003_remove_userprofile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
