# Generated by Django 3.2.12 on 2025-01-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndani4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.CharField(default='default_task_id', max_length=255, unique=True),
        ),
    ]
