# Generated by Django 3.2.12 on 2025-01-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndani4', '0002_task_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='payment_status',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='transaction_screenshot',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='transactions/'),
        ),
    ]
