# Generated by Django 3.2.12 on 2025-02-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndani4', '0003_auto_20250131_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='transaction_screenshot',
        ),
    ]
